inherit_from:
  - https://raw.githubusercontent.com/RoleModel/shared_rubocop/master/.rubocop.yml

# Add your definitions below.
# For pre-existing projects, you can run `rubocop --auto-gen-config` to exclude current issues without making them worse!
